CREATE TABLE device_catalog
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    quantity  INT CHECK ( quantity > 0 ),
    price DOUBLE PRECISION CHECK ( price > 0 ),
    created_date DATE,
    updated_date DATE
);